pipeline {
  agent any

  stages {
    stage('Setup Python venv') {
      steps {
        sh '''
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r lab2/requirements.txt
        '''
      }
    }

    stage('Download data')   {
      steps { sh '. venv/bin/activate && python lab2/src/download_data.py' }
    }

    stage('Preprocess data') {
      steps { sh '. venv/bin/activate && python lab2/src/preprocess_data.py' }
    }

    stage('Train model')     {
      steps { sh '. venv/bin/activate && python lab2/src/model_training.py' }
    }

    stage('Evaluate')        {
      steps { sh '. venv/bin/activate && python lab2/src/test_model.py' }
    }
  }

  post {
    success {
      archiveArtifacts artifacts: 'lab2/models/model.pkl', fingerprint: true
      archiveArtifacts artifacts: 'lab2/reports/metrics.json', fingerprint: true
    }
    always {
      archiveArtifacts artifacts: 'lab2/data/processed/**/*', fingerprint: true
    }
  }
}